# 一个基本的工作流
# 1、安装linux系统
# 2、安装go、设置go环境
# 3、pull代码
# 4、编译go
# 5、打包go
# 6、部署go

# 工作流的名称
name: build-go

# 工作流运行的前提条件
on:
  push:
    branches: [ master ]
  # pull_request:
  #   branches: [ master ]

  # 允许手动运行工作流
  workflow_dispatch: 

# 工作流由n个job(任务)组成，这些job可以顺序执行或者并发执行
jobs:
  # 编译工程
  build:
    # job的名称
    name: 编译

    # 运行job所需的操作系统环境
    runs-on: ubuntu-latest

    # job包含的step(步骤)
    steps:
      # 拉取代码
      - name: 拉取代码
        uses: actions/checkout@v2
      
      # 安装go
      - name: 安装go
        uses: actions/setup-go@v2

      # 设置go环境
      - name: 开启go mod
        run: |
          export GO111MODULE=on
          go env

      # go build
      - name: 运行go build
        id : build
        run: |
          go build test.go

  # 测试：功能测试和性能测试
  test:
    # 需要先执行build任务
    needs: [build]

    # job的名称
    name: 测试

    # 运行job所需的操作系统环境
    runs-on: ubuntu-latest

    # job包含的step(步骤)
    steps:
      - name: 功能测试
        env:  #设置该步骤需要用到的环境变量
          MY_VAR: Hi there! My name is
          FIRST_NAME: Allen
          MIDDLE_NAME: To
          LAST_NAME: Zhu
        run: 
          echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.

      - name: 性能测试
        env:  #设置该步骤需要用到的环境变量
          MY_VAR: Hi there! My name is
          FIRST_NAME: Allen
          MIDDLE_NAME: To
          LAST_NAME: Zhu
        run: 
          echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.

  # 部署：客户端部署到Github Release或公司官网、服务端部署到公司正式服
  deploy:
    # 需要先执行build和test任务
    needs: [build,test]
    
    # job名称
    name: 部署

    # 运行job所需的操作系统环境
    runs-on: ubuntu-latest

    # job包含的step(步骤)
    steps:
      - name: 上传到Github Release
        uses: svenstaro/upload-release-action@v2
        with:
          # Github token
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          # 需要上传的二进制文件
          file: ./test
          # 需要上传的二进制文件名
          asset_name: test
          # 本次上传打的tag
          tag: ${{ github.ref }}
          # 是否覆盖
          overwrite: true
          # 说明
          body: "This is my release readme file"
  
