# 一个基本的工作流
# 1、安装linux系统
# 2、安装go、设置go环境
# 3、pull代码
# 4、编译go
# 5、打包go
# 6、部署go

# 工作流的名称
name: build-go

# 工作流运行的前提条件
on: [
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
]
  # 允许手动运行工作流
  workflow_dispatch: 

# 工作流由一个或多个job(任务)组成，这些job可以顺序执行或者并发执行
jobs:
  # 本工作流包含一个job，叫作build
  build:
    # 运行工作流所需的操作系统环境
    runs-on: ubuntu-latest

    # 一个job由许多step(步骤)组成
    steps:
      - uses: actions/checkout@v2
      - name: 拉取代码
      
      #- name: 安装go
      #- uses: actions/setup-go@v2

      - name: 运行单一命令
        run: echo Hello, world!

      - name: 运行一系列命令
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
