# 一个基本的工作流文件
# 1、安装linux系统
# 2、安装go、设置go环境
# 3、pull代码
# 4、编译go
# 5、打包go
# 6、部署go

# 工作流的名称
name: build-go

# 工作流运行的前提条件
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # 允许手动运行工作流
  workflow_dispatch: on

# 工作流由一个或多个job(任务)组成，这些job可以顺序执行或者并发执行
jobs:
  # 本工作流包含一个job，叫作build
  build:
    # 运行工作流所需的操作系统环境
    runs-on: ubuntu-latest

    # 一个job由许多step(步骤)组成
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
