# 工作流的名称
name: build-qt

# 工作流运行的前提条件
on:
  push:
    branches: [ test-branch ]
  # pull_request:
  #   branches: [ master ]

  # 允许手动运行工作流
  workflow_dispatch: 

jobs:
  upload:
    # job的名称
    name: 编译

    # 运行job所需的操作系统环境
    runs-on: ubuntu-latest

    # job包含的step(步骤)
    steps:
      # 拉取代码
      - uses: actions/checkout@v2

      # 上传到Github Release
      - name: upload release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tags:
          file: ./test.go
          tags: false
          draft: false